:- use_module(library(clpfd)).
:- use_module(library(random)).
:- use_module(library(lists)).
:- use_module(library(system)).
:- consult('display.pl').
:- consult('menu.pl').
:- consult('utils.pl').
:- consult('puzzle.pl').
:- consult('teste.pl').
